-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 21:14:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema rocketleague
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rocketleague
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rocketleague` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `rocketleague` ;

-- -----------------------------------------------------
-- Table `rocketleague`.`jogador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocketleague`.`jogador` (
  `idJogador` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idJogador`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rocketleague`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocketleague`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(15) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(30) NULL DEFAULT NULL,
  `senha` VARCHAR(10) NULL DEFAULT NULL,
  `fkJogador` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_usuario_jogador1_idx` (`fkJogador` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_jogador1`
    FOREIGN KEY (`fkJogador`)
    REFERENCES `rocketleague`.`jogador` (`idJogador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rocketleague`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocketleague`.`avaliacao` (
  `idAvaliacao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(1000) NULL DEFAULT NULL,
  `fkPlayer` INT NOT NULL,
  `fkUser` INT NOT NULL,
  PRIMARY KEY (`idAvaliacao`, `fkUser`, `fkPlayer`),
  INDEX `fkPlayer` (`fkPlayer` ASC) VISIBLE,
  INDEX `fkUser` (`fkUser` ASC) VISIBLE,
  CONSTRAINT `fkPlayer`
    FOREIGN KEY (`fkPlayer`)
    REFERENCES `rocketleague`.`jogador` (`idJogador`),
  CONSTRAINT `fkUser`
    FOREIGN KEY (`fkUser`)
    REFERENCES `rocketleague`.`usuario` (`idUsuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `rocketleague`.`pontuacaoquiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rocketleague`.`pontuacaoquiz` (
  `idPontuacao` INT NOT NULL AUTO_INCREMENT,
  `acertos` INT NULL DEFAULT NULL,
  `pontuacao` INT NULL DEFAULT NULL,
  `fkUsuario` INT NOT NULL,
  PRIMARY KEY (`idPontuacao`, `fkUsuario`),
  INDEX `fkUsuario` (`fkUsuario` ASC) VISIBLE,
  CONSTRAINT `fkUsuario`
    FOREIGN KEY (`fkUsuario`)
    REFERENCES `rocketleague`.`usuario` (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
